[server]
socket = "/tmp/oxcache.sock"
disk = "/dev/nvme3n1"
writer_threads = 1
reader_threads = 1
chunk_size = 268435456

[remote]
remote_type = "emulated" # emulated | S3
bucket = "S3_BUCKET"

[eviction]
eviction_policy = "promotional"
high_water_evict = 1 # Number remaining from end, evicts if reaches here
low_water_evict = 3  # Evict until below mark