[server]
socket = "/tmp/oxcache.sock"
disk = "/dev/zd48"
writer_threads = 14
reader_threads = 14
chunk_size = 8192

[remote]
remote_type = "emulated" # emulated | S3
bucket = "S3_BUCKET"

[eviction]
eviction_policy = "dummy"
num_evict = 1
high_water_evict = 3
low_water_evict = 1