#include "libnvme_wrapper.h"

// inline or static functions can't be generated by Bindgen
int nvme_zns_report_zones_wrapper(int fd, __u32 nsid, __u64 slba,
				  enum nvme_zns_report_options opts,
				  bool extended, bool partial,
				  __u32 data_len, void *data,
				  __u32 timeout, __u32 *result) {
  return nvme_zns_report_zones(fd, nsid, slba, opts, extended, partial, data_len, data, timeout, result);
}
