[package]
name = "oxcache"
version = "0.1.0"
edition = "2024"

[dependencies]
libnvme-sys = { path = "../libnvme-sys" }
nvme = { path = "../nvme" }
dashmap = "7.0.0-rc2"
config = "0.15.11"
serde = { version = "1.0.219", features = ["derive"] }
clap = { version = "4.5.38", features = ["derive"] }
toml = "0.8.22"