[package]
name = "libnvme-sys"
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
bindgen = "0.71.0"
cc = "1.2.23"

[profile.dev.package."*"]
opt-level = 3

# [build]
# rustflags = ["-lnvme"]